@EasyWorkout.Api_HostAddress = https://localhost:7011
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwYzgxYzNiNy0zZDUzLTQ3YjMtYWFiMi1hZWNhZTUyODliYWEiLCJzdWIiOiJUZXN0QWRkVXNlckRiMyIsIm5hbWUiOiJMYXJyeSBTbWl0aCIsInVzZXJpZCI6IjAxOWIzZGUyLWUzZDUtNzdkOC05YWZiLTAyYWY5YTIwNTgyNyIsImZyZWVfbWVtYmVyIjoidHJ1ZSIsIm5iZiI6MTc2Njc3MTQwMCwiZXhwIjoxNzY2NzcyMzAwLCJpYXQiOjE3NjY3NzE0MDAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMzMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDExIn0.yEcm-gT85Xs98YtolZQNcczE5jvO34jBnapS-qsgoMY


GET {{EasyWorkout.Api_HostAddress}}/api/workouts/me
Authorization: Bearer {{token}}
###

@id=577d4457-b393-4236-a92b-8b12fb44ff40
POST {{EasyWorkout.Api_HostAddress}}/api/exercises/{{id}}/sets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "setNumber": 3
}

###

@exerciseSetId = 083e30e6-9cfe-47f7-9555-f08756fea3d9
DELETE {{EasyWorkout.Api_HostAddress}}/api/exercises/{{id}}/sets/{{exerciseSetId}}
Authorization: Bearer {{token}}
###


@id = 019b3de2-e3d5-77d8-9afb-02af9a205827
GET {{EasyWorkout.Api_HostAddress}}/api/users/{{id}}
Authorization: Bearer {{token}}
###


PUT {{EasyWorkout.Api_HostAddress}}/api/users/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Larry",
  "lastName": "Smith"
}

###

POST {{EasyWorkout.Api_HostAddress}}/api/completed-workouts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "completedDate": "2012-04-23T18:25:43.511Z",
  "completedExerciseSets": [

  ],
  "completedNotes": null,
  "workoutId": "1bbfa6c4-2f03-40c0-b0d4-2abbb2de1a54"
}

###

