@EasyWorkout.Identity.Api_HostAddress = https://localhost:7033


###

POST {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "TestAddUserDb3",
  "password": "@Hunter3"
}

###


POST {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{       
  "userName": "TestAddUserDb3",
  "email": "fakeemail@sdfkd.com",
  "password": "@Hunter3",
  "firstName": "Jimmy",
  "lastName": "McIntosh"
}

###
