@EasyWorkout.Identity.Api_HostAddress = https://localhost:7033


###

POST {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "TestAddUserDb3",
  "password": "@Hunter3"
}

###


POST {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{       
  "userName": "TestAddUserDb3",
  "email": "fakeemail@sdfkd.com",
  "password": "@Hunter3",
  "firstName": "Jimmy",
  "lastName": "McIntosh"
}

###


POST {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "GWAW1Q+XqJERLLEId0ZrpLJInZC1rktEAlDYi35zlLQpJ+VA+5dd7L6nTb5jRun5zkrAjuE59BdPhKO9vj4R3g=="
}

###


@refreshToken=GWAW1Q+XqJERLLEId0ZrpLJInZC1rktEAlDYi35zlLQpJ+VA+5dd7L6nTb5jRun5zkrAjuE59BdPhKO9vj4R3g==
DELETE {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/revoke/{{refreshToken}}

###
