@EasyWorkout.Identity.Api_HostAddress = https://localhost:7033


###

POST {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "TestAddUserDb2",
  "password": "@Hunter2"
}

###


POST {{EasyWorkout.Identity.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{       
  "userName": "TestAddUserDb2",
  "email": "fakeemail@sdfkd.com",
  "password": "@Hunter2",
  "firstName": "Jane",
  "lastName": "McElroy"
}

###
