// <auto-generated />
using System;
using EasyWorkout.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyWorkout.Application.Migrations
{
    [DbContext(typeof(WorkoutsContext))]
    [Migration("20260101174600_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedNotes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("CompletedWorkoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("FallbackName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedWorkoutId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("CompletedExercises");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedExerciseId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("DurationUnit")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExerciseSetId")
                        .HasColumnType("uuid");

                    b.Property<double?>("GoalDuration")
                        .HasColumnType("double precision");

                    b.Property<int?>("GoalReps")
                        .HasColumnType("integer");

                    b.Property<double?>("GoalWeight")
                        .HasColumnType("double precision");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompletedExerciseId");

                    b.ToTable("CompletedExerciseSets");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedNotes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FallbackName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<DateTime>("LastEditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("CompletedWorkouts");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AddedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastEditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("DurationUnit")
                        .HasColumnType("text");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AddedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastEditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciseNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedExercise", b =>
                {
                    b.HasOne("EasyWorkout.Application.Model.CompletedWorkout", null)
                        .WithMany("CompletedExercises")
                        .HasForeignKey("CompletedWorkoutId");

                    b.HasOne("EasyWorkout.Application.Model.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedExerciseSet", b =>
                {
                    b.HasOne("EasyWorkout.Application.Model.CompletedExercise", null)
                        .WithMany("CompletedExerciseSets")
                        .HasForeignKey("CompletedExerciseId");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedWorkout", b =>
                {
                    b.HasOne("EasyWorkout.Application.Model.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.ExerciseSet", b =>
                {
                    b.HasOne("EasyWorkout.Application.Model.Exercise", null)
                        .WithMany("ExerciseSets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.WorkoutExercise", b =>
                {
                    b.HasOne("EasyWorkout.Application.Model.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyWorkout.Application.Model.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedExercise", b =>
                {
                    b.Navigation("CompletedExerciseSets");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.CompletedWorkout", b =>
                {
                    b.Navigation("CompletedExercises");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.Exercise", b =>
                {
                    b.Navigation("ExerciseSets");

                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("EasyWorkout.Application.Model.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
